[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first_multi'
sort_imports = true

[profile.default]
solc_version = '0.8.26'
libs = ['node_modules', 'lib']
optimizer_runs = 10_000
via_ir = true
memory_limit = 43554432
gas_limit = "18446744073709551615"
fallback_oz = true
is_system = false
mode = "3"


[profile.optimized]
out = 'out-via-ir'

[profile.test]
via_ir = true
out = 'out-via-ir'

[profile.docs]
src = 'src/interfaces/'

[fuzz]
runs = 1000

[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
sepolia = "${SEPOLIA_RPC}"
zksync = "https://rpc.testnet.lens.xyz"

